name: ArgoCD Deployment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      DOCKER_IMAGE_TAG:
        required: false
        type: string
      APP_NAME:
        required: true
        type: string
      APP_NAME_SHORT:
        required: false
        type: string
        default: ${{ github.event.inputs.APP_NAME }}
      AWS_REGION:
        required: false
        type: string
        default: "us-east-1"

    secrets:
      GH_WORKFLOW_TOKEN:
        required: true
      ARGOCD_TOKEN:
        required: true
      OIDC_IAM_ROLE:
        required: true


jobs:
  check_org:
    name: Check Caller
    runs-on: ubuntu-latest

    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'trafilea' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by Trafilea.')

  deploy:
    needs: check_org
    name: Deploy
    runs-on: ubuntu-latest

    env:
      ENV: ${{ inputs.ENVIRONMENT }}
      IMAGE_TAG: ${{ inputs.DOCKER_IMAGE_TAG }}
      APP_NAME: ${{ inputs.APP_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Clone GitOps Repo
        uses: actions/checkout@v3
        with:
          repository: trafilea/trafilea-gitops
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
      
      - name: Configure AWS Credentials
        id: oidc
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
          aws-region: "${{ inputs.AWS_REGION }}"

      - name: Generate new ConfigMap
        env:
          project_name: ${{ inputs.APP_NAME }}
          project_name_short: ${{ inputs.APP_NAME_SHORT }}
          version: ${{ inputs.DOCKER_IMAGE_TAG }}
          environment: ${{ inputs.ENVIRONMENT }}
        run: |
          aws s3 cp s3://trafilea-apps-config/$project_name/eks/$environment/$version.env ./new-config/.env
          echo "Environment variables copied successfully."
          echo "Generating ConfigMap..."
          kubectl create configmap $project_name_short-config --namespace=trafilea --from-env-file=./new-config/.env --dry-run=client -o yaml > ./new-config/configmap.yaml
          cp ./new-config/configmap.yaml apps/overlays/$ENV/$APP_NAME/configmap.yaml
          rm -rf ./new-config
          echo "ConfigMap generated successfully."

      - name: Replace Image Tag
        run: |
          OLD_TAG=$(cat apps/overlays/$ENV/$APP_NAME/$APP_NAME.yaml | grep tag: | awk '{print $2}')
          sed -i "s/tag: $OLD_TAG/tag: $IMAGE_TAG/g" apps/overlays/$ENV/$APP_NAME/$APP_NAME.yaml

      - name: Configure Git User creds
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Actions"

      - name: Stage changes
        run: git add .

      - name: Commit new file
        run: git diff-index --quiet HEAD || git commit -m "Updating $APP_NAME version on $ENV environment"

      - name: Push changes
        run: git push origin main
      
      - name: Set destination
        id: setdest
        run: |
          if [ ${{ inputs.ENVIRONMENT }}  == 'dev' ]; then echo "SERVER_ADDRESS=argo.development.trafilea.app" >> $GITHUB_OUTPUT; elif [ ${{ inputs.ENVIRONMENT }}  == 'stage' ]; then echo "SERVER_ADDRESS=argo.staging.trafilea.app" >> $GITHUB_OUTPUT; else echo "SERVER_ADDRESS=argo.production.trafilea.app" >> $GITHUB_OUTPUT; fi
          sleep 5

      - name: Sync ArgoCD Application
        uses: omegion/argocd-actions@v1
        with:
          address: ${{ steps.setdest.outputs.SERVER_ADDRESS }}
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: applications
