name: Deploy Static Content
on:
  workflow_call:
    inputs:
      PRELOAD_IMAGES_PATH:
        required: true
        type: string

    secrets:
      OPS_AWS_ACCESS_KEY_ID:
        required: true
      OPS_AWS_SECRET_ACCESS_KEY:
        required: true
      GH_WORKFLOW_TOKEN:
        required: true

jobs:
  check_org:
    name: Check Caller
    runs-on: ubuntu-latest

    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'trafilea' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by Trafilea.')

  deploy:
    needs: check_org
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Clone preload action definition
        uses: actions/checkout@v4
        with:
          repository: trafilea/action-trafilea-cdn-image-preload
          ref: 'main'
          fetch-depth: 0
          path: ./.github/action-trafilea-cdn-image-preload
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}

      - name: Preload images
        id: preload-images
        uses: ./.github/action-trafilea-cdn-image-preload
        with:
          images: ${{inputs.PRELOAD_IMAGES_PATH}}
