name: Upload to S3 and Invalidate Cloudfront

on:
  workflow_call:
    inputs:
      BUCKET_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      AWS_REGION:
        required: false
        default: "us-east-1"
        type: string
      BUILD_FOLDER:
        required: false
        default: dist
        type: string
      BUILD_COMMAND:
        required: true
        type : string


    secrets:
      OPS_AWS_ACCESS_KEY_ID:
        required: true
      OPS_AWS_SECRET_ACCESS_KEY:
        required: true
      GH_WORKFLOW_TOKEN:
        required: true


jobs:
  check_org:
    name: Check Caller
    runs-on: ubuntu-latest

    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'trafilea' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by Trafilea.')

  deploy:
    needs: check_org
    name: Deploy
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION}}
      ENV: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://foo:${{ secrets.GH_WORKFLOW_TOKEN }}@github.com/trafilea".insteadOf "https://github.com/trafilea"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.OPS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.OPS_AWS_SECRET_ACCESS_KEY  }}
          aws-region: "${{ inputs.AWS_REGION }}"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.2.9

      - name: Install Terragrunt
        uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: 0.36.12


      - name: Run the build command
        run: |
          ${{ inputs.BUILD_COMMAND }}

      - name: Get Cloudfront Distribution Domain
        id: cloudfront-dist-id
        working-directory: ./terraform/environment/${{ inputs.ENVIRONMENT }}/cloudfront
        run: |
          export CLOUDFRONT_DOMAIN_NAME=`terragrunt output | grep "cloudfront_distribution_domain ="| awk '{print $3}' | tr -d '"'`
          echo "cloudfront_dist_id=$CLOUDFRONT_DOMAIN_NAME" >> $GITHUB_OUTPUT

      - name: S3 Upload and Cloudfront Invalidation
        uses: reggionick/s3-deploy@v3
        with:
          folder: ${{ inputs.BUILD_FOLDER }}
          bucket: ${{ inputs.BUCKET_NAME  }}
          bucket-region: us-east-1
          dist-id: ${{ steps.cloudfront-dist-id.outputs.cloudfront_dist_id }}
          invalidation: /
          delete-removed: true