name: Run terraform plan

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      AWS_REGION:
        required: false
        default: "us-east-1"
        type: string
      DOCKER_IMAGE_TAG:
        required: false
        default: any
        type: string
      PACKAGE_VERSION:
        required: false
        default: some-ver
        type: string
      INFRA_PATH:
        required: false
        default: terraform
        type: string
      TERRAFORM_VERSION:
        required: false
        type: string
        default: 1.2.9
      TERRAGRUNT_VERSION:
        required: false
        type: string
        default: 0.36.12          

    secrets:
      OIDC_IAM_ROLE:
        required: true
      GH_WORKFLOW_TOKEN:
        required: true
      DB_PASSWORD:
        required: false
      TE_DD_API_KEY:
        required: true
      TE_DD_APP_KEY:
        required: false

jobs:
  check_org:
    name: Check Caller
    runs-on: ubuntu-latest

    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'trafilea' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by Trafilea.')

  deploy:
    needs: check_org
    name: Test Infra
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION}}
      TF_VAR_docker_image_tag: ${{ inputs.DOCKER_IMAGE_TAG }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
      ENV: ${{ inputs.ENVIRONMENT }}
      DD_API_KEY: ${{ secrets.TE_DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.TE_DD_APP_KEY }}
      TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}
      TERRAGRUNT_VERSION: ${{ inputs.TERRAGRUNT_VERSION }}
      TG_DOWNLOAD_DIR: ${{ github.workspace }}/.terragrunt-cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://foo:${{ secrets.GH_WORKFLOW_TOKEN }}@github.com/trafilea".insteadOf "https://github.com/trafilea"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
          aws-region: "${{ inputs.AWS_REGION }}"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: ${{ inputs.TERRAFORM_VERSION }}

      - name: Install Terragrunt
        uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ inputs.TERRAGRUNT_VERSION }}

      - name: Terragrunt Plan
        run: terragrunt run-all plan -lock=false --terragrunt-non-interactive --terragrunt-source-update --terragrunt-include-external-dependencies -no-color
        working-directory: ${{ github.workspace }}/${{ inputs.INFRA_PATH }}/environment/${{ inputs.ENVIRONMENT }}/
