name: Run terraform plan

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      AWS_REGION:
        required: false
        default: "us-east-1"
        type: string
      DOCKER_IMAGE_TAG:
        required: false
        default: any
        type: string
      PACKAGE_VERSION:
        required: false
        default: some-ver
        type: string

    secrets:
      GH_WORKFLOW_TOKEN:
        required: true
      DB_PASSWORD:
        required: false

jobs:
  check_org:
    name: Check Caller
    runs-on: ubuntu-latest

    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'trafilea' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by Trafilea.')

  directories:
    needs: check_org
    name: "Directory-changes"
    runs-on: ubuntu-latest
    steps:
      - uses: theappnest/terraform-monorepo-action@master
        id: directories
        with:
          monitored: '.hcl'
      - run: echo ${{ steps.directories.outputs.modules }}
    outputs:
      dirs: ${{ steps.directories.outputs.modules }}

  deploy:
    needs: directories
    name: Test Infra
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directories: ${{ fromJson(needs.directories.outputs.dirs) }}
    env:
      AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION}}
      TF_VAR_docker_image_tag: ${{ inputs.DOCKER_IMAGE_TAG }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
      ENV: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://foo:${{ secrets.GH_WORKFLOW_TOKEN }}@github.com/trafilea".insteadOf "https://github.com/trafilea"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
          aws-region: "${{ inputs.AWS_REGION }}"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: 1.2.9

      - name: Install Terragrunt
        uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: 0.36.12

      - name: Terragrunt Plan
        run: terragrunt plan -lock=false --terragrunt-non-interactive --terragrunt-source-update --terragrunt-include-external-dependencies -no-color
        if: contains($${ matrix.directories }}, 'terraform/core/environment/ops/**')
        working-directory: contains($${ matrix.directories }}, 'terraform/core/environment/ops/**')
