name: Test Go Application workflow


on:
  workflow_call:
    inputs:
      GO_VERSION:
        required: true
        type: number

    secrets:
      GH_WORKFLOW_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  check_org:
    name: Check calling organization
    runs-on: ubuntu-latest

    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'trafilea' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by Trafilea.')


  build_n_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -coverprofile coverage/coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
