name: Deploy using Terragrunt

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      DOCKER_IMAGE_TAG:
        required: false
        type: string


    secrets:
      GH_WORKFLOW_TOKEN:
        required: true

jobs:
  check_org:
    name: Check Caller
    runs-on: ubuntu-latest

    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'trafilea' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by Trafilea.')

  deploy:
    needs: check_org
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      
      - name: Read contents of environment file
        run: |
          yq -o=json eval variables-${{ github.event.inputs.ENVIRONMENT }}.yaml | jq -c > contents.json
          EnvironmentFileContents=$(cat contents.json)
          echo "EnvironmentFileContents=$EnvironmentFileContents" >> $GITHUB_ENV 
          echo $EnvironmentFileContents

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          repository: trafilea/trafilea-services-infra
          event-type: deploy-ecs
          client-payload: '{"appName":"${{ github.event.inputs.APP_NAME }}","environment":"${{ github.event.inputs.ENVIRONMENT }}","dockerImageTag":"${{ github.event.inputs.DOCKER_IMAGE_TAG }}","envVariables":${{ env.EnvironmentFileContents }}}'
