name: Upload Storefront Static to S3

on:
  workflow_call:
    inputs:
      BUILDS_BUCKET:
        required: true
        type: string
      AWS_REGION:
        required: false
        default: "us-east-1"
        type: string
      PACKAGE_NAME:
        required: true
        type: string
      PACKAGE_VERSION:
        required: true
        type: string

    secrets:
      OPS_AWS_ACCESS_KEY_ID:
        required: true
      OPS_AWS_SECRET_ACCESS_KEY:
        required: true
      GH_WORKFLOW_TOKEN:
        required: true


jobs:
  check_org:
    name: Check Caller
    runs-on: ubuntu-latest

    steps:
      - name: Check the calling organization
        if: ${{ github.repository_owner != 'trafilea' }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This reusable workflow can only be used by Trafilea.')

  upload:
    needs: check_org
    name: Upload
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          submodules: true
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
      
      - name: Configure AWS Credentials
        id: configure-credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.OPS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.OPS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Build and Zip package
        run: |
          rm -f README.md
          zip -r ${{ inputs.PACKAGE_NAME}}-${{ inputs.PACKAGE_VERSION }}.zip . -x '.github/*'
      
      - name: Upload build to Amazon S3
        env:
          PACKAGE_FILE: ${{ inputs.PACKAGE_NAME}}-${{ inputs.PACKAGE_VERSION }}.zip
          AWS_S3_BUCKET: ${{ inputs.BUILDS_BUCKET }}
          PROJECT_NAME: ${{ inputs.PACKAGE_NAME }}
        run: |
          aws s3 cp $PACKAGE_FILE s3://$AWS_S3_BUCKET/$PROJECT_NAME/$PACKAGE_FILE
